First 2023 events
ZeusWPI/zeus.ugent.be pull request #562
Opened 2022-12-29 22:35 UTC by smessie

2022-12-29 23:03 UTC, klaasg requested changes

2022-12-29 23:03 UTC, klaasg commented on content/events/22-23/12urenloop_intro.md
> +end: '20-02-2022 20:00'
```suggestion
time: '20-02-2023 19:00' 
end: '20-02-2023 20:00'
```

2022-12-29 23:03 UTC, klaasg commented on content/events/22-23/12urenloop_intro.md
> +
```suggestion
Het is ook een beetje een generale repitite voor de 12urenloop in Gent.

```

2022-12-29 23:19 UTC, smessie commented on content/events/22-23/IHNGTWHSIPB.md
> +Waarom één project doen als je ook twee projecten kan doen?
't is dag 4 ;)

2022-12-29 23:20 UTC, klaasg commented on content/events/22-23/IHNGTWHSIPB.md
> +Waarom één project doen als je ook twee projecten kan doen?
Tis Zeus dus we tellen vanaf 0 😉

2022-12-29 23:24 UTC, klaasg approved these changes

2022-12-30 23:13 UTC, FKD13 commented on content/events/22-23/IHNGTWHSIPB.md
> +DAT KAN NIET! Het is letterlijk dag 3 van het semester!
Is de 16e niet de 4e dag :D

2023-01-01 21:15 UTC, merged